packages:
  - .
verifyDepsBeforeRun: error
minimumReleaseAge: 1440
minimumReleaseAgeExcludePrune: true
shellEmulator: true
trustPolicy: no-downgrade
minimumReleaseAgeExclude:
  - "@ztd-me/*"
trustPolicyExclude:
  - semver@6.3.1
